### ISSUE TITLE
Generating BED targets

### ISSUE THREAD

**Issue by Asutu** [mozack/abra2#12]
Hi,
do you have any recommended way of generating the BED targets file to give to ABRA2 --targets. I know that
"The targets argument is not required. When omitted, the entire genome will be eligible for realignment."
but I guess that specifying a targets file could potentialy speed up the ABRA2 process.

**Comment by mozack** [comment]
This really depends on your specific situation.

If you are only interested in specific genes / exons, then specify those loci.

If you have targeted sequencing, then you may wish to specify the capture target loci.

If you're interested in coding regions only, you may consider using the exons defined in the Gencode GTF: https://www.gencodegenes.org/releases/current.html . If you go this route you'll want to duplicate / overlapping exon definitions.  bedtools merge / slop is useful for this sort of thing : http://bedtools.readthedocs.io/en/latest/

**Comment by Asutu** [comment]
Thanks. That was helpful. Will try to do as suggested.
