### ISSUE TITLE
Using abra/abra2 for local assembly of pacbio reads?

### ISSUE THREAD

**Issue by ggstatgen** [mozack/abra2#20]
Hi

Just stumbled on your interesting project and was wondering if you had thoughts regarding its applicability to pacbio DNA reads. Essentially, I have 13x WGS pacbio data  for a mouse strain and, having tried to map to mm10, I get a large gap of little/no mapping in a locus of interest. The gap is approx 400Kb wide and my average read length is 15Kb.  

I want to find out whether this is a large deletion or maybe just a repetitive region, or a combination of both. I thought I'd try locally assembling the pacbio reads to find out whether, without the mm10 reference, they assemble in an uninterrupted contig or not. The latter would perhaps indicate a very repetitive region. 

Would abra/abra2 be of help in this scenario? Thanks in any case!

**Comment by mozack** [comment]
Hi,

To date, we have only tested with Illumina reads and with much shorter assembly regions (i.e. 400nt is the default in the current version) with the intent of improving detection of short to moderate length indels.  I would be skeptical about using ABRA2 for PacBio reads and/or 400kb deletions at this time.
