### ISSUE TITLE
Invalid read written

### ISSUE THREAD

**Issue by marc-sturm** [mozack/abra2#22]
Hi,

I have re-analyzes our samples with ABRA2 (they were done initially with ABRA), and encountered one case where it runs through, but the output BAM file is not valid:
>#make indel_realign
java -jar /mnt/share/opt/abra2_2.17/abra2-2.17.jar --in SIBPlatte2A11_01.bam --out SIBPlatte2A11_01_realign.bam --target-kmers kmers.bed --threads 4 --ref /tmp/local_ngs_data//GRCh37.fa --mer 0.1 > indel_realign.log 2>&1
samtools index SIBPlatte2A11_01_realign.bam
[E::bam_read1] CIGAR and query sequence lengths differ for D00388:195:CAUD5ANXX:6:2208:3316:13407
samtools index: failed to create index for "SIBPlatte2A11_01_realign.bam"

You can download a minimal example that reproduces the problem here:
https://drive.google.com/open?id=1IGFE24lNmTrElvCLqwHPEcdf4-zrwwMk
You just have to adapt the paths for abra2, samtools and GRCh37.

Best,
  Marc

**Comment by mozack** [comment]
Thanks for the bug report and test data.  This should be fixed in release 2.18.  Please let me know if you continue to run into problems.
