### ISSUE TITLE
MD tags for realigned reads

### ISSUE THREAD

**Issue by rawagiha** [mozack/abra2#31]
I am using abra2.2.19.  Thanks a lot for this great tool.

Is it possible to update MD tags of realigned reads? 
They are using the tags based on the original alignments. 
Also, some realigned reads do not have MD at all.

Thanks,

**Comment by mozack** [comment]
Yes, we will look into addressing this in an upcoming release.

**Comment by rawagiha** [comment]
Thank you so much for your consideration!

**Comment by mozack** [comment]
Hi,  I am finally looping back to this and seeing that the MD format is not so straightforward and difficult to use.  Is supporting for this still of interest?

**Comment by rawagiha** [comment]
Thanks again for caring about this issue. For now, I can use the realigned reads with the MD feature.
