### ISSUE TITLE
Abra2 output BAM processing

### ISSUE THREAD

**Issue by roysomak4** [mozack/abra2#34]
Thanks for this software. Very useful in my WES/targeted sequencing workflow!

I have a question about the processing requirements of the BAM file generated by ABRA2. Per documentation of ABRA (original version), it states "_It is currently necessary to sort and index the output. At present, the mate information may not be 100% accurate. Samtools fixmate or Picard Tools FixMateInformation may optionally be used to correct this._" 
Is this still a requirement for the realigned BAM file generated by ABRA2? I did not see this in the documentation for ABRA2.

Thank you!

**Comment by mozack** [comment]
By default, the output of ABRA2 is sorted and the mate locus is set properly.  The --index param can be used to generate the BAM index, however we have at times seen this use excessive memory.  samtools index usually runs in a few minutes and may be a more consistent option for now.

**Comment by roysomak4** [comment]
@mozack, Thank you for the clarification!
