### ISSUE TITLE
abra 2.07 removes half of pair completely

### ISSUE THREAD

**Issue by lordzappo** [mozack/abra2#5]
Thank you for writing abra.  I am currently in the process of upgrading to abra 2.07 from abra 1.XXX.

For many of my samples, abra 2 works ok, but for at least one, it removes one half of a paired read completely.  This leaves a read with RNEXT/PNEXT set, but it's mate doesn't appear in the file. 

This is uncaught by default, and unfixable generally, for picard FixMateInformation.  This can cause various picard tools to fail downstream of any abra operation. 

Is this behaviour by design?  Recommendations to make this bam work, short of removing the erroneous reads by hand? Thanks! CCH

**Comment by lordzappo** [comment]
I should say we previously ran FixMateInformation after abra 1 and that produced an acceptable bam.

During testing abra 2.07, we are getting more errors after fixmate, like cigar maps off end of reference. 

I am trying to clean these up with CleanSam, but it isn't fixing them.

**Comment by mozack** [comment]
Hi,

We don't use Picard often.  For the rare cases when I do use Picard, I typically set VALIDATION_STRINGENCY to silent.  FixMateInformation should not be necessary as of 2.07.

Reads hanging off the end of the chromosome should generally not cause any practical issues and you might consider ignoring that specific issue temporarily.  I will have a fix for this in a forthcoming release.

Half of a read pair being dropped is definitely not by design and sounds like a more serious bug.  Do you have a dataset you could share that reproduces the issue?

**Comment by lordzappo** [comment]
I'm sorry for the delay, I am still inquiring who owns what dataset, and the one that generated the issue turned out to be unsuitable for sharing.  but I do intend to deliver you an example.

running validatesamfile produces this on different data, which I think I can share.
## HISTOGRAM    java.lang.String
Error Type  Count
ERROR:MATE_NOT_FOUND    14500


For you to reproduce, you need: the slice of the pre-abra bam that contains the read names I find with validatesamfile as MATE NOT FOUND.  Is that correct?   Any other requirements?  Minimum width of slice? Just enough to contain one seemingly broken read? 100s of broken reads?

**Comment by mozack** [comment]
Thanks for following up.  A BAM file that passes ValidateSAMFile pre-ABRA2 and contains at least a handful of reads with the MATE_NOT_FOUND problem would be great.  If the BAM is small enough to email, that would be perfect.

**Comment by lordzappo** [comment]
Ok, on closer inspection as I went to prepare the file, this is actually that picard fix mate information can do harmful things to the bam after abra.  We plugged 2.07 in directly to current pipeline that previously ran abra1.   I wrongly assumed fixmateinformation was incapable of evil. 

IMO this is closed but if you want more information to add a caveat to the readme, I would be glad to provide.
