### ISSUE TITLE
the software is great ,but i still has a problom,it will leave some reads un-gapped,like the figure show,i want known why those reads un-gapped? if those reads gapped,they all are perfect match the del,and have no mismatches. 

### ISSUE THREAD

**Issue by 522845911** [mozack/abra2#8]
![image](https://user-images.githubusercontent.com/21213861/30636265-84e5e984-9e27-11e7-8904-f3032397773d.png)

**Comment by mozack** [comment]
There can be a variety of reasons.   A few examples where we do not realign: the read may map equally well to multiple alignments.  The initial mapping quality may be lower than the mininum (default: 20).  The location of the read's mate may be greater than the allowed distance (default: 1000).  There may be other causes.

At least 2 of the reads in your example do not appear to exactly match the gap.

If you'd like to share a BAM snippet and the details of your run, I can give you a definitive answer.
